[tool.poetry]
name = "bitvector-for-humans"
version = "0.14.1"
description = "A simple pure python Bit Vector class for Humans™."
authors = ["JnyJny <erik.oshaughnessy@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/JnyJny/bitvector.git"
packages = [{include = "bitvector" }]
include = ["bitvector/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^6"
coverage = "^5"
mypy = "^0.790"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = ["fast: fast tests", "slow: slow tests"]
